### ISSUE TITLE
[Section] License

### ISSUE THREAD

**Issue by IuryAlves** [IuryAlves/system-design-primer#29]

**Comment by rubensantoniorosa2704** [comment]
Estou distribuindo os códigos e recursos deste repositório sob uma licença de código aberto. Sendo este o meu repositório pessoal, a licença que você está recebendo dos códigos e dos recursos aqui presentes é de minha posse, e não do meu empregador (Facebook).

2017 - Todos os direitos reservados à Donne Martin

Licença Creative Commons Atribuição 4.0 Internacional (CC BY 4.0)

http://creativecommons.org/licenses/by/4.0/
![Captura de tela de 2023-04-19 11-31-18](https://user-images.githubusercontent.com/86082354/233108095-f956604e-5575-4a42-9c0d-0bb834c21843.png)

**Comment by IuryAlves** [comment]
Oi @rubensantoniorosa2704,

Obrigado pela sua contribuição! Eu não estou mais mantendo esse projeto. Você pode criar um Pull Request pro projeto original: https://github.com/donnemartin/system-design-primer

**Comment by rubensantoniorosa2704** [comment]
Olá, @IuryAlves, obrigado pelo feedback.
